model:
  model_name: deepseekV3
  graph: false
  graph_file: /home/dcg/GOFA/graphs.txt

system:
  gpu_gen: B100 # e.g. A100, H100, B100, B200 (currently only support 4 generation)
  nvlink_gen: 5
  infiniband_gen: 800
  num_node: 1
  num_device: 8
  processor_type: GPU
  distribution:
    expert_tensor_degree: 1
    none_expert_tensor_degree: 1
  optimization:
    parallel_execution: false
    hetero_subbatch: false
    disagg_system: false
    use_low_unit_moe_only: false
    use_ramulator: false
    compressed_kv: true
    use_absorb: true
    use_flash_mla: true
    use_flash_attention: true
    reuse_kv_cache: false
    kv_cache_reuse_rate: 0.0
    prefill_mode: false
    decode_mode: true

serving:
  max_batch_size: 32
  max_process_token: 0

simulation:
  data: synthesis
  input_len: 1024
  output_len: 1
  precision_byte: 1
  skewness: 0.0
  iter: 5
  injection_rate: 0
  exit_out_of_memory: false
  mem_cap_limit: false # if memory usage exceed memory capacity, batchsize modifies

log:
  print_log: true
  export_gantt: false
  output_directory: ../data/
  gantt_directory: ./gantt
