model:
  model_name: mixtral
  graph: on
  graph_file: /home/dcg/GOFA/graphs.txt

system:
  gpu_gen: B100 # e.g. A100, H100, B100, B200 (currently only support 4 generation)
  nvlink_gen: 5
  infiniband_gen: 800
  num_node: 1
  num_device: 1
  processor_type: GPU+LOGIC
  distribution:
    expert_tensor_degree: 1
    none_expert_tensor_degree: 1
  optimization:
    parallel_execution: off
    hetero_subbatch: off
    disagg_system: off
    use_low_unit_moe_only: off
    use_ramulator: off
    compressed_kv: on
    use_absorb: on
    use_flash_mla: on
    use_flash_attention: on
    reuse_kv_cache: off
    kv_cache_reuse_rate: 0.0
    prefill_mode: on
    decode_mode: off

serving:
  max_batch_size: 32
  max_process_token: 0

simulation:
  data: synthesis
  input_len: 1024
  output_len: 1
  precision_byte: 1
  skewness: 0.0
  iter: 5
  injection_rate: 0
  exit_out_of_memory: off
  mem_cap_limit: off # if memory usage exceed memory capacity, batchsize modifies

log:
  print_log: on
  export_gantt: on
  output_directory: /home/dcg/LLMSimulator/build/log
  gantt_directory: /home/dcg/LLMSimulator/build/gantt